version: 2
enable-beta-ecosystems: true
updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-loader'
          - 'babel-plugin-module-resolver'
          - 'babel-plugin-transform-import-meta'
          - 'clean-webpack-plugin'
          - 'copy-webpack-plugin'
          - 'terser-webpack-plugin'
          - 'tsx'
          - 'webpack'
          - 'webpack-*'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'typescript'

      logging:
        patterns:
          - '@elastic/ecs-pino-format'
          - '*-pino'
          - '*-pino-format'
          - 'hapi-pino'
          - 'pino'
          - 'pino-*'

      tools:
        patterns:
          - 'babel-jest'
          - 'husky'
          - 'jest'
          - 'jest-*'
          - 'nodemon'
          - 'npm-run-all'

      types:
        patterns:
          - '@types/*'

    ignore:
      # Upgrade to Node LTS versions only
      - dependency-name: '@types/node'
        versions: [">=23"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

  # Update Dockerfiles
  - package-ecosystem: docker
    directory: /

    ignore:
      # Upgrade to Node LTS versions only
      - dependency-name: 'node'
        versions: [">=23"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

  # Update Docker Compose files
  - package-ecosystem: docker-compose
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
