// This file is auto-generated from: src/api/common/models/invoices.js
// Do not edit this file directly! Use: npm run generate:model-types

/**
 * @typedef {object} Invoice
 * @property {string} agreementNumber ID of the agreement this invoice is for
 * @property {string} invoiceNumber The invoice ID
 * @property {string} correlationId The correlation ID for tracking
 * @property {Record<string, any> | undefined} [paymentHubRequest]
 */
